version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: technodom-backend
    restart: always
    env_file:
      - packages/backend/.env
    environment:
      - PORT=4000
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
    ports:
      - "4000:4000"
    depends_on:
      - minio
    networks:
      - technet

  frontend:
    build:
      context: .
      dockerfile: packages/techno-dom/Dockerfile
    container_name: technodom-frontend
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - technet

  minio:
    image: minio/minio
    container_name: technodom-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - technet

networks:
  technet:
    driver: bridge

volumes:
  minio_data:
